import { Info, ShieldCheck, X } from 'lucide-react';
import { useState } from 'react';

const STORAGE_KEY = 'sih26108.disclaimer.dismissed';

interface Props {
  /** Compact single-line form for the standard detail page. */
  variant?: 'full' | 'inline';
  message?: string;
}

/**
 * Persistent, non-dismissible-in-spirit notice: this prototype must never be
 * mistaken for an official BIS system, and match scores must never read as a
 * compliance verdict. The full variant can be collapsed for the session.
 */
export function DisclaimerBanner({ variant = 'full', message }: Props) {
  const [dismissed, setDismissed] = useState<boolean>(
    () => sessionStorage.getItem(STORAGE_KEY) === '1',
  );

  if (dismissed) return null;

  if (variant === 'inline') {
    return (
      <p className="flex items-start gap-1.5 text-xs leading-relaxed text-amber-900">
        <Info aria-hidden className="mt-0.5 h-3.5 w-3.5 shrink-0" />
        <span>
          {message ??
            'Prototype output, not a BIS certification or compliance decision. Match scores are computed by this application.'}
        </span>
      </p>
    );
  }

  return (
    <div className="border-b border-amber-200 bg-amber-50">
      <div className="mx-auto flex max-w-7xl items-start gap-3 px-4 py-2.5 sm:px-6 lg:px-8">
        <ShieldCheck aria-hidden className="mt-0.5 h-4 w-4 shrink-0 text-amber-700" />
        <p className="flex-1 text-xs leading-relaxed text-amber-900">
          <span className="font-semibold">Research prototype — not an official BIS system.</span>{' '}
          {message ??
            'Recommendations and match scores are generated by this application from a demonstration knowledge base using publicly described metadata. They are not a Bureau of Indian Standards certification, approval or compliance statement. Verify the applicable standard, its current edition and amendments with BIS before finalising any procurement.'}
        </p>
        <button
          type="button"
          onClick={() => {
            sessionStorage.setItem(STORAGE_KEY, '1');
            setDismissed(true);
          }}
          aria-label="Dismiss prototype notice for this session"
          className="-m-1 shrink-0 rounded p-1 text-amber-700 transition-colors hover:bg-amber-100"
        >
          <X aria-hidden className="h-3.5 w-3.5" />
        </button>
      </div>
    </div>
  );
}
